[package]
name = "Albert"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12.4", default-features = false, features = ["client", "gateway", "rustls_backend", "model"]}
tokio = { version = "1.34.0", features = ["full"] }
dotenv = "0.15"